import type { Destination, ImageAsset } from "@/lib/types";

/**
 * The five hero-quality photographs currently in use across the site — some
 * owned by Noble Path, one (`sigiriyaSunrise`) freely-licensed stock swapped
 * in 2026-09-20 to replace a low-resolution original. `credit` records which
 * is which. Until the owned library is complete (requirements §7.3) every
 * other destination, experience and package reuses the closest of these
 * five. `alt` always describes the photograph that is actually rendered,
 * never the page it sits on, because a screen-reader user must be told what
 * is really on screen. Tracked as a known limitation.
 *
 * Exported from this module (rather than a separate file) so that experiences
 * and trips share one definition of each photograph's alt text and credit.
 */
export const ownedPhotos = {
  sigiriyaSunrise: {
    src: "/images/hero/sigiriya-sunrise-2.jpg",
    alt: "Sigiriya rock fortress rising out of dense jungle under a dramatic sunset sky, storm clouds breaking to gold light.",
    credit: "Photo by Marina Zvada / Pexels",
  },
  ellaRoadSign: {
    src: "/images/destinations/ella.jpg",
    alt: "Travellers on a tuk-tuk beside the Ella road sign on a misty hill-country road.",
    credit: "Noble Path photo library",
  },
  surfSouthCoast: {
    src: "/images/experiences/surfing-south-coast.jpg",
    alt: "Two surfers carrying boards along a palm-lined beach at dusk.",
    credit: "Noble Path photo library",
  },
  jungleVilla: {
    src: "/images/experiences/jungle-villa-yala.jpg",
    alt: "Aerial view of a thatched jungle villa and its pool surrounded by dense forest.",
    credit: "Noble Path photo library",
  },
  tuktukRoadTrip: {
    src: "/images/experiences/tuktuk-road-trip.jpg",
    alt: "Travellers skateboarding behind a tuk-tuk on an empty palm-lined road.",
    credit: "Noble Path photo library",
  },
} as const satisfies Record<string, ImageAsset>;

/**
 * All destinations (FR-1).
 *
 * Seasonality follows Sri Lanka's two opposing monsoons: the Yala monsoon soaks
 * the south-west roughly May–September, the Maha monsoon soaks the north-east
 * roughly November–February, and October–November is a wet inter-monsoon almost
 * everywhere. Drive times are advisory estimates for typical road conditions
 * (requirements §7.5) and are treated as bidirectional by the travel graph.
 */
export const destinations: readonly Destination[] = [
  /* ---------------------------------------------------------------- west */
  {
    slug: "colombo",
    name: "Colombo",
    region: "west-coast",
    tagline: "The island's loud, layered, rapidly changing front door",
    summary:
      "Sri Lanka's commercial capital is a working port city rather than a resort, and it is far more interesting for it. Colonial arcades, Buddhist and Hindu temples, a Dutch hospital turned dining quarter and some of the best food on the island sit within a few square kilometres. Most visitors give it half a day; a full day is better rewarded.",
    description: [
      "Colombo is not a city that announces itself. Its pleasures are specific rather than monumental: the Pettah market's street-by-street specialisation, the Sea Street goldsmiths, the red-and-white striped Jami Ul-Alfar mosque, an evening on Galle Face Green with isso wade and a kite.",
      "The old Dutch Hospital precinct in Fort has been restored into restaurants and shops and is the easiest entry point if your time is short. From there the Gangaramaya temple, the Independence Memorial and the National Museum form a comfortable half-day loop by tuk-tuk.",
      "Eat well here. Colombo has the country's broadest range — hoppers and kottu from street stalls, Tamil and Muslim cooking in Pettah and Slave Island, and a serious modern Sri Lankan restaurant scene that has grown up in the last decade.",
      "Practically, Colombo is a transit hub more than a base. The airport is 35 km north near Negombo, the Southern Expressway reaches Galle in about ninety minutes, and trains to Kandy and the hill country leave from Fort station early in the morning.",
    ],
    interests: ["culture", "food"],
    bestMonths: [12, 1, 2, 3],
    shoulderMonths: [4, 7, 8, 11],
    avoidMonths: [5, 6, 9, 10],
    seasonNote:
      "Pleasant and dry from December to March. The south-west monsoon brings heavy afternoon rain from May, and October is the wettest month of the year.",
    suggestedNights: 1,
    image: ownedPhotos.tuktukRoadTrip,
    highlights: [
      "Pettah market and the Jami Ul-Alfar mosque",
      "The restored Dutch Hospital precinct in Fort",
      "Gangaramaya temple and Beira Lake",
      "Sunset and street food on Galle Face Green",
      "The National Museum for context before the Cultural Triangle",
    ],
    travel: [
      { to: "negombo", minutes: 50, note: "Traffic-dependent; allow longer in the evening peak." },
      { to: "kandy", minutes: 210 },
      { to: "galle", minutes: 95, note: "Via the Southern Expressway (E01)." },
      { to: "dambulla", minutes: 235 },
      { to: "hikkaduwa", minutes: 85 },
      { to: "udawalawe", minutes: 225 },
    ],
    coordinates: { lat: 6.9271, lng: 79.8612 },
    experienceSlugs: ["colombo-street-food-walk"],
    nearbySlugs: ["negombo", "hikkaduwa", "kandy"],
    appeal: 70,
  },
  {
    slug: "negombo",
    name: "Negombo",
    region: "west-coast",
    tagline: "Twenty minutes from the airport, and a beach at the end of it",
    summary:
      "Negombo exists on most itineraries as a first or last night, and it does that job unusually well. The airport is a 20–30 minute drive away, the beach is wide and walkable, and the fishing harbour and Dutch-era canal give the town more character than a transit stop deserves.",
    description: [
      "Arrive on a long-haul flight and the last thing you want is four hours in a car. Negombo lets you sleep, swim and eat within half an hour of landing, then start the real trip the next morning.",
      "The town itself is strongly Catholic — a legacy of Portuguese rule — with churches at the centre of village life and a fishing fleet that comes in at dawn. The Lellama fish market is genuinely worth the early start, and the lagoon behind the town is best seen from a small boat at first light.",
      "The Dutch canal that runs north from the lagoon was cut in the seventeenth century to move cinnamon to Colombo. Parts are now a quiet paddling and cycling route through coconut plantations and villages.",
      "Negombo is also the traditional starting point for a self-drive tuk-tuk trip, and a cluster of Ayurveda and wellness resorts sits along this stretch of coast.",
    ],
    interests: ["beach", "food", "wellness"],
    bestMonths: [12, 1, 2, 3],
    shoulderMonths: [4, 7, 8, 11],
    avoidMonths: [5, 6, 9, 10],
    seasonNote:
      "Calm sea and reliable sunshine December to March. Swimming is often unwise during the south-west monsoon from May to September.",
    suggestedNights: 1,
    image: ownedPhotos.surfSouthCoast,
    highlights: [
      "Lellama fish market at dawn",
      "The Dutch canal by boat or bicycle",
      "Negombo lagoon and its stilt-legged fishing craft",
      "A first or last night within 30 minutes of the airport",
      "Long-established Ayurveda retreats along the coast",
    ],
    travel: [
      { to: "colombo", minutes: 50 },
      { to: "sigiriya", minutes: 240 },
      { to: "kandy", minutes: 185 },
      { to: "anuradhapura", minutes: 195 },
      { to: "wilpattu", minutes: 180 },
    ],
    coordinates: { lat: 7.2083, lng: 79.8358 },
    experienceSlugs: ["negombo-lagoon-and-canal-boat", "ayurveda-wellness-retreat", "tuktuk-road-trip"],
    nearbySlugs: ["colombo", "wilpattu", "kandy"],
    appeal: 58,
  },
  /* ---------------------------------------------------- cultural triangle */
  {
    slug: "sigiriya",
    name: "Sigiriya",
    region: "cultural-triangle",
    tagline: "A fifth-century sky palace on a two-hundred-metre rock",
    summary:
      "Sigiriya is the image most people carry of Sri Lanka before they arrive, and it survives the expectation. King Kassapa built a fortified palace on the summit of a granite monolith in the fifth century, surrounded by symmetrical water gardens that still fill in the rains. Climb it early, before the heat and the queues.",
    description: [
      "The ascent is around 1,200 steps through the lion's paws, past the mirror wall and a sheltered gallery of frescoes, onto a summit plateau of brick foundations, bathing pools and very large views. It takes most people two to three hours in total.",
      "Start at 7am when the gates open. By 9am the metal stairways are hot and crowded, and by midday the exposed rock is punishing. The alternative is the late afternoon slot, which is cooler but means descending close to dusk.",
      "Across the road, Pidurangala rock is a rougher, cheaper, scramble-at-the-top climb that looks straight at Sigiriya. Many travellers now do Pidurangala at sunrise and Sigiriya itself later, or on the following morning.",
      "Sigiriya village is the most practical base for the whole Cultural Triangle: Dambulla is 30 minutes away, Polonnaruwa a little over an hour, and Minneriya and Kaudulla national parks are on the doorstep for the dry-season elephant gathering.",
    ],
    interests: ["culture", "adventure", "nature"],
    bestMonths: [5, 6, 7, 8, 9],
    shoulderMonths: [1, 2, 3, 4, 12],
    avoidMonths: [10, 11],
    seasonNote:
      "Dry-zone climate: clearest and driest May to September. October and November are the wettest months and the rock can close in high wind.",
    suggestedNights: 2,
    image: ownedPhotos.sigiriyaSunrise,
    highlights: [
      "The summit palace and water gardens at opening time",
      "The fresco gallery and the mirror wall",
      "Pidurangala rock for the view back at Sigiriya",
      "Minneriya or Kaudulla for the dry-season elephant gathering",
      "Village cycling through paddy and tank bunds",
    ],
    travel: [
      { to: "dambulla", minutes: 30 },
      { to: "polonnaruwa", minutes: 75 },
      { to: "anuradhapura", minutes: 110 },
      { to: "kandy", minutes: 155 },
      { to: "trincomalee", minutes: 165 },
    ],
    coordinates: { lat: 7.957, lng: 80.7603 },
    experienceSlugs: ["sigiriya-sunrise-climb", "pidurangala-sunrise", "minneriya-elephant-gathering"],
    nearbySlugs: ["dambulla", "polonnaruwa", "anuradhapura"],
    appeal: 98,
  },
  {
    slug: "dambulla",
    name: "Dambulla",
    region: "cultural-triangle",
    tagline: "Five caves, one hundred and fifty Buddhas, two thousand years",
    summary:
      "The Golden Temple of Dambulla is the largest and best-preserved cave temple complex in Sri Lanka. Five chambers cut into an overhanging rock hold more than 150 statues and some 2,100 square metres of painted ceiling, continuously maintained since the first century BCE. It is a 20-minute climb and an hour well spent.",
    description: [
      "Each cave has its own character, from the single 14-metre reclining Buddha carved out of the rock in the first chamber to the crowded, richly painted Maha Alut Viharaya. The murals follow the contours of the cave roof rather than a flat surface, which is what makes them remarkable.",
      "It is an active temple. Shoulders and knees must be covered, shoes come off at the terrace, and you should never turn your back on a Buddha image for a photograph — a rule that is taken seriously and occasionally enforced.",
      "Dambulla town itself is a junction rather than a destination, but it holds the country's largest wholesale vegetable market and is the cheapest place in the region to base yourself if Sigiriya's village hotels are full.",
      "Most travellers visit Dambulla as a half-day stop between Sigiriya and Kandy, which works well: the caves in the morning, lunch in town, and on the road by early afternoon.",
    ],
    interests: ["culture"],
    bestMonths: [5, 6, 7, 8, 9],
    shoulderMonths: [1, 2, 3, 4, 12],
    avoidMonths: [10, 11],
    seasonNote: "Dry and hot May to September; heaviest rain in October and November.",
    suggestedNights: 1,
    image: ownedPhotos.sigiriyaSunrise,
    highlights: [
      "Cave 1: the 14-metre rock-cut reclining Buddha",
      "The painted ceilings of the Maha Alut Viharaya",
      "The terrace view over the dry-zone plain to Sigiriya",
      "Dambulla wholesale market at first light",
    ],
    travel: [
      { to: "sigiriya", minutes: 30 },
      { to: "kandy", minutes: 110 },
      { to: "anuradhapura", minutes: 90 },
      { to: "polonnaruwa", minutes: 90 },
      { to: "colombo", minutes: 235 },
    ],
    coordinates: { lat: 7.8675, lng: 80.6511 },
    experienceSlugs: ["dambulla-cave-temple"],
    nearbySlugs: ["sigiriya", "polonnaruwa", "kandy"],
    appeal: 78,
  },
  {
    slug: "polonnaruwa",
    name: "Polonnaruwa",
    region: "cultural-triangle",
    tagline: "A medieval capital you can cycle around in a morning",
    summary:
      "Sri Lanka's second ancient capital was at its height in the twelfth century under Parakramabahu I, and its ruins are unusually compact, well-labelled and shaded. The Gal Vihara's four colossal Buddha figures, carved from a single granite face, are among the finest stone sculpture in South Asia.",
    description: [
      "Polonnaruwa rewards a bicycle. The site is flat, the ruins are spread over a few kilometres of quiet lanes under trees, and you can cover the Royal Palace, the Quadrangle, the Rankot Vehera and the Gal Vihara comfortably in three to four hours.",
      "The Quadrangle is the dense heart of it — the Vatadage's circular relic house, the Hatadage, the stone book of the Gal Pota — and repays slow looking. The Gal Vihara sits at the north end and is usually kept for last.",
      "Beside the city lies the Parakrama Samudra, a vast twelfth-century reservoir that still irrigates the district. Elephants come down to drink on its fringes in the late afternoon, and the bund is a good place to end the day.",
      "Go early. There is little shade on the open platforms by mid-morning, and the site's own toque macaques become increasingly interested in unattended bags as the day warms up.",
    ],
    interests: ["culture", "adventure"],
    bestMonths: [5, 6, 7, 8, 9],
    shoulderMonths: [1, 2, 3, 4, 12],
    avoidMonths: [10, 11],
    seasonNote: "Hot and dry May to September. The north-east monsoon brings real rain from late October into December.",
    suggestedNights: 1,
    image: ownedPhotos.sigiriyaSunrise,
    highlights: [
      "The four Buddha figures of the Gal Vihara",
      "The Vatadage and the Quadrangle",
      "Cycling the site under shade in the early morning",
      "Parakrama Samudra reservoir at dusk",
      "The archaeological museum's scale models",
    ],
    travel: [
      { to: "sigiriya", minutes: 75 },
      { to: "dambulla", minutes: 90 },
      { to: "trincomalee", minutes: 125 },
      { to: "anuradhapura", minutes: 120 },
      { to: "kandy", minutes: 185 },
    ],
    coordinates: { lat: 7.9403, lng: 81.0188 },
    experienceSlugs: ["polonnaruwa-cycle-tour"],
    nearbySlugs: ["sigiriya", "dambulla", "trincomalee"],
    appeal: 74,
  },
  {
    slug: "anuradhapura",
    name: "Anuradhapura",
    region: "cultural-triangle",
    tagline: "A living sacred city, 1,400 years in the making",
    summary:
      "Anuradhapura was the island's capital for over a millennium and remains one of Buddhism's most important pilgrimage sites. Its scale is the point: enormous brick stupas, monastic cities, and the Sri Maha Bodhi, grown from a cutting of the tree under which the Buddha attained enlightenment and tended continuously since the third century BCE.",
    description: [
      "This is not a museum piece. White-clad pilgrims walk the sacred precinct every day, and the atmosphere at the Ruwanwelisaya at dusk — oil lamps, lotus offerings, chanting — is the reason to come rather than the archaeology.",
      "The site is far larger than Polonnaruwa and is best covered by car with a driver or by bicycle if you are used to heat. Allow a full day for the sacred city, the Abhayagiri and Jetavanarama complexes and the Isurumuniya rock temple.",
      "The Sri Maha Bodhi is the oldest documented living tree planted by human hand anywhere in the world. Dress code is strict and cameras are restricted close to the terrace.",
      "Anuradhapura is also the natural staging point for Wilpattu National Park, an hour to the west, and for the long run north to Jaffna.",
    ],
    interests: ["culture", "nature"],
    bestMonths: [5, 6, 7, 8, 9],
    shoulderMonths: [1, 2, 3, 4, 12],
    avoidMonths: [10, 11],
    seasonNote: "Driest May to September. October to December can be genuinely wet under the north-east monsoon.",
    suggestedNights: 1,
    image: ownedPhotos.sigiriyaSunrise,
    highlights: [
      "Ruwanwelisaya stupa at dusk with the evening pilgrims",
      "The Sri Maha Bodhi sacred fig",
      "Abhayagiri monastery and the Samadhi Buddha",
      "Isurumuniya's carved lovers",
      "Twin Ponds (Kuttam Pokuna) stonework",
    ],
    travel: [
      { to: "dambulla", minutes: 90 },
      { to: "sigiriya", minutes: 110 },
      { to: "wilpattu", minutes: 75 },
      { to: "jaffna", minutes: 210 },
      { to: "trincomalee", minutes: 165 },
      { to: "negombo", minutes: 195 },
    ],
    coordinates: { lat: 8.3114, lng: 80.4037 },
    experienceSlugs: ["anuradhapura-sacred-city-tour"],
    nearbySlugs: ["wilpattu", "sigiriya", "jaffna"],
    appeal: 72,
  },
  /* --------------------------------------------------------- hill country */
  {
    slug: "kandy",
    name: "Kandy",
    region: "hill-country",
    tagline: "The last kingdom, around a lake, in the hills",
    summary:
      "Kandy held out against European powers until 1815 and still feels like the island's cultural centre of gravity. The Temple of the Sacred Tooth Relic sits on the lake at its heart, and the city is the gateway to the tea country and the starting point of the hill-country railway.",
    description: [
      "The Sri Dalada Maligawa houses a tooth relic of the Buddha and is the most venerated Buddhist site in the country. Time your visit to one of the three daily puja ceremonies, when the inner chamber is opened and the drummers play; arrive thirty minutes early and dress modestly.",
      "Beyond the temple, Kandy is a walking city: the lake circuit, the covered market, the Kandy Garrison Cemetery, and an uphill climb to the Bahiravakanda Buddha for the view back over the rooftops.",
      "The Royal Botanic Gardens at Peradeniya, six kilometres out of town, hold 147 acres of orchid house, giant bamboo, a cannonball tree avenue and an enormous Javan fig — an easy, shaded half-day.",
      "Kandy is where most travellers pick up the train south. The Kandy–Nanu Oya–Ella line is slow, often full, and worth every minute; book reserved seats well in advance or take a second-class unreserved carriage and stand in the doorway with everyone else.",
    ],
    interests: ["culture", "nature"],
    bestMonths: [1, 2, 3, 4],
    shoulderMonths: [5, 6, 7, 8, 9, 12],
    avoidMonths: [10, 11],
    seasonNote:
      "Cooler than the coast all year. Driest January to April; October and November bring the heaviest rain. The Esala Perahera festival falls in July or August.",
    suggestedNights: 2,
    image: ownedPhotos.ellaRoadSign,
    highlights: [
      "Evening puja at the Temple of the Sacred Tooth Relic",
      "The Royal Botanic Gardens at Peradeniya",
      "Boarding the hill-country train to Ella",
      "The lake circuit walk at dusk",
      "Kandyan dance and drumming at the cultural centre",
    ],
    travel: [
      { to: "colombo", minutes: 210, note: "Longer on Sunday evenings; the train is slower but scenic." },
      { to: "dambulla", minutes: 110 },
      { to: "sigiriya", minutes: 155 },
      { to: "nuwara-eliya", minutes: 165 },
      { to: "ella", minutes: 240, mode: "road", note: "The train takes 6–7 hours and is the point of the journey." },
      { to: "adams-peak", minutes: 210 },
      { to: "negombo", minutes: 185 },
    ],
    coordinates: { lat: 7.2906, lng: 80.6337 },
    experienceSlugs: ["temple-of-the-tooth", "kandy-to-ella-train", "royal-botanic-gardens-peradeniya"],
    nearbySlugs: ["nuwara-eliya", "dambulla", "sigiriya"],
    appeal: 90,
  },
  {
    slug: "nuwara-eliya",
    name: "Nuwara Eliya",
    region: "hill-country",
    tagline: "Tea, mist and a half-remembered English winter",
    summary:
      "At 1,868 metres, Nuwara Eliya is the highest town in Sri Lanka and the centre of the tea industry. The British built it as a hill station and it has never quite stopped being one — hedges, a racecourse, a post office out of 1900 — set among some of the steepest, greenest tea estates in the world.",
    description: [
      "The tea is the reason to come. Estates around the town run factory tours that take you from plucking through withering, rolling, oxidation and firing in about forty minutes, ending with a tasting that will change how you buy tea at home.",
      "The town divides opinion. Some find it charmingly odd, others find it damp and chilly. Both are right — it can drop below 10°C at night and the mist rolls in most afternoons, so pack a jacket, which nobody expects to need in Sri Lanka.",
      "Gregory Lake is the centre of local leisure, Victoria Park is a good birding stop for hill-country endemics, and Lover's Leap waterfall is a short walk from the edge of town.",
      "Nanu Oya station, 15 minutes away, is where most travellers join or leave the Kandy–Ella train, and Horton Plains is about an hour and a quarter up the road for a pre-dawn start.",
    ],
    interests: ["nature", "culture", "food"],
    bestMonths: [1, 2, 3, 4],
    shoulderMonths: [5, 6, 7, 8, 9, 12],
    avoidMonths: [10, 11],
    seasonNote:
      "Clearest and coldest January to April, which is also the local holiday season in April. Expect afternoon mist year-round and heavy rain in October and November.",
    suggestedNights: 2,
    image: ownedPhotos.ellaRoadSign,
    highlights: [
      "A working tea factory tour and tasting",
      "The estate roads above the town at first light",
      "Gregory Lake and the colonial-era town centre",
      "Victoria Park for endemic hill-country birds",
      "Nanu Oya station for the train to Ella",
    ],
    travel: [
      { to: "kandy", minutes: 165 },
      { to: "ella", minutes: 120, note: "The train covers the same route in about 3 hours and is far more enjoyable." },
      { to: "horton-plains", minutes: 75 },
      { to: "adams-peak", minutes: 150 },
    ],
    coordinates: { lat: 6.9497, lng: 80.7891 },
    experienceSlugs: ["tea-estate-and-factory-tour", "kandy-to-ella-train"],
    nearbySlugs: ["ella", "horton-plains", "kandy"],
    appeal: 80,
  },
  {
    slug: "ella",
    name: "Ella",
    region: "hill-country",
    tagline: "A gap in the mountains with the whole south below it",
    summary:
      "Ella is a one-street hill town that happens to sit at the head of a spectacular gap in the escarpment, with views that run all the way to the southern plains on a clear morning. It is the hill country's social centre — hikes, waterfalls, the Nine Arch Bridge and more banana-pancake cafés than the population justifies.",
    description: [
      "The two classic walks leave from the village. Little Adam's Peak is an easy 45-minute climb for sunrise. Ella Rock is a harder two to three hours each way along the railway line and up through tea and eucalyptus, and is genuinely easy to get lost on without a guide or a downloaded track.",
      "The Nine Arch Bridge, built in stone and brick without steel during the First World War, curves through the jungle below Ella. Check the train times locally and be on the bridge or the viewpoint for a crossing — it is the difference between a nice bridge and a memorable one.",
      "Ella sits in the Uva rain shadow, which gives it a different season to most of the hill country: it is often bright and clear in July and August while the western slopes are wet, and wettest from October into December.",
      "The town has become busy, and that is worth knowing in advance. Stay a few hundred metres outside the centre, start early, and it is still one of the most enjoyable places on the island.",
    ],
    interests: ["nature", "adventure", "food", "wellness"],
    bestMonths: [2, 3, 4, 7, 8, 9],
    shoulderMonths: [1, 5, 6],
    avoidMonths: [10, 11, 12],
    seasonNote:
      "Uva sits in a rain shadow, so Ella is often clear in July and August when the south-west is wet. Its own rain arrives October to December.",
    suggestedNights: 2,
    image: ownedPhotos.ellaRoadSign,
    highlights: [
      "Little Adam's Peak at sunrise",
      "A train crossing the Nine Arch Bridge",
      "Ella Rock for the harder, quieter climb",
      "Ravana Falls and the hot springs road down to Wellawaya",
      "Arriving by train from Nanu Oya or Kandy",
    ],
    travel: [
      { to: "nuwara-eliya", minutes: 120 },
      { to: "kandy", minutes: 240 },
      { to: "horton-plains", minutes: 120 },
      { to: "yala", minutes: 150 },
      { to: "udawalawe", minutes: 120 },
      { to: "arugam-bay", minutes: 180 },
      { to: "mirissa", minutes: 240 },
    ],
    coordinates: { lat: 6.8667, lng: 81.0466 },
    experienceSlugs: [
      "little-adams-peak-and-nine-arch",
      "ella-rock-sunrise-hike",
      "ella-yoga-morning",
      "kandy-to-ella-train",
    ],
    nearbySlugs: ["nuwara-eliya", "horton-plains", "udawalawe"],
    appeal: 95,
  },
  {
    slug: "horton-plains",
    name: "Horton Plains",
    region: "hill-country",
    tagline: "Cloud forest, frost hollows, and a 900-metre drop",
    summary:
      "Horton Plains is a high plateau of montane grassland and cloud forest at over 2,000 metres, and the only national park in Sri Lanka you are allowed to walk in unaccompanied. The 9 km circuit takes in Baker's Falls and World's End, where the plateau simply stops and falls away towards the southern plains.",
    description: [
      "You have to be early. The escarpment clouds over almost every morning between about 9 and 10am, and after that World's End is a view of white. That means leaving Nuwara Eliya or Ohiya around 5am, in the cold and dark.",
      "The loop is well-marked, takes three to four hours at a steady pace, and is not technically difficult — but it is at altitude, the ground is uneven, and it can be close to freezing at the start and hot by the end. Layers, proper shoes and water.",
      "The grassland holds sambar deer in numbers, and the forest patches shelter several endemic birds and the occasional purple-faced langur. Leopards are present and essentially never seen.",
      "There is no accommodation inside the park. Most people stay at Nuwara Eliya, Ohiya or Ella and treat Horton Plains as a long, early day trip. All plastic is checked at the gate and must be carried back out.",
    ],
    interests: ["nature", "adventure", "wildlife"],
    bestMonths: [1, 2, 3],
    shoulderMonths: [4, 5, 6, 7, 8, 9, 12],
    avoidMonths: [10, 11],
    seasonNote:
      "Clearest skies January to March. Whatever the month, be at World's End before 9am or the view will be cloud.",
    suggestedNights: 1,
    image: ownedPhotos.ellaRoadSign,
    highlights: [
      "World's End before the cloud arrives",
      "Baker's Falls on the return leg",
      "Montane cloud forest and sambar deer on the grassland",
      "The drive up through Ambewela's dairy farms",
    ],
    travel: [
      { to: "nuwara-eliya", minutes: 75 },
      { to: "ella", minutes: 120 },
      { to: "kandy", minutes: 210 },
      { to: "adams-peak", minutes: 180 },
    ],
    coordinates: { lat: 6.8096, lng: 80.8016 },
    experienceSlugs: ["horton-plains-worlds-end"],
    nearbySlugs: ["nuwara-eliya", "ella", "adams-peak"],
    appeal: 68,
  },
  {
    slug: "adams-peak",
    name: "Adam's Peak (Sri Pada)",
    region: "hill-country",
    tagline: "Five thousand steps, in the dark, with thousands of pilgrims",
    summary:
      "Sri Pada is sacred to Buddhists, Hindus, Muslims and Christians alike, and has drawn pilgrims for at least a thousand years. The climb from Nallathanniya is around 5,500 steps in the dark, timed to reach the 2,243-metre summit for sunrise and the peak's famous triangular shadow.",
    description: [
      "The season runs from the December Unduvap full moon to the May Vesak full moon. In season the path is lit, tea stalls are open through the night, and on poya weekends it can be shoulder-to-shoulder the whole way up.",
      "Outside the season the lights are off, the stalls are shut and the weather is often appalling. It can still be climbed, but it becomes a serious unsupported night hike rather than a pilgrimage.",
      "Most climbers start between 2 and 2.30am and take three to four hours up. It is relentless stair-climbing rather than technical walking, and the last section is steep. Take warm layers for the summit wait — it is cold and windy up there.",
      "The descent is hard on the knees and takes two to three hours in daylight, with views over the Peak Wilderness Sanctuary that you climbed straight past in the dark.",
    ],
    interests: ["adventure", "culture", "nature"],
    bestMonths: [1, 2, 3, 4],
    shoulderMonths: [5, 12],
    avoidMonths: [6, 7, 8, 9, 10, 11],
    seasonNote:
      "Pilgrimage season runs from the December full moon to the May full moon; outside it the path is unlit, facilities are closed and the weather is usually poor.",
    suggestedNights: 1,
    image: ownedPhotos.ellaRoadSign,
    highlights: [
      "Sunrise from the summit and the peak's triangular shadow",
      "Climbing through the night with pilgrims and tea stalls",
      "The Peak Wilderness Sanctuary on the way down",
      "Tea estates and waterfalls around Hatton and Dalhousie",
    ],
    travel: [
      { to: "nuwara-eliya", minutes: 150 },
      { to: "kandy", minutes: 210 },
      { to: "colombo", minutes: 240 },
      { to: "horton-plains", minutes: 180 },
    ],
    coordinates: { lat: 6.8096, lng: 80.4994 },
    experienceSlugs: ["adams-peak-night-climb"],
    nearbySlugs: ["nuwara-eliya", "kandy", "horton-plains"],
    appeal: 66,
  },
  /* ---------------------------------------------------------- south coast */
  {
    slug: "galle",
    name: "Galle",
    region: "south-coast",
    tagline: "A Dutch fort on a headland, still lived in",
    summary:
      "Galle Fort is a walled seventeenth-century town on a promontory, and it is the most complete European-built fortification in Asia. Inside the ramparts are coral-stone churches, a working lighthouse, boutique hotels in merchant houses, and streets that people still live and trade on rather than a preserved shell.",
    description: [
      "Walk the ramparts at sunset. The full circuit takes about an hour, passes the lighthouse and the Flag Rock bastion where local boys dive into the sea for tips, and gives you the shape of the place before you walk its streets.",
      "Inside the walls, the Dutch Reformed Church, the old Dutch Hospital, the Maritime Museum and the Historical Mansion fill a slow morning. The pleasure of Galle, though, is aimless wandering — jewellers, bookshops, cafés in eighteenth-century courtyards.",
      "The fort is small and can be covered in a day, but it is a good base for the wider south. Unawatuna, Koggala's stilt fishermen, Handunugoda tea estate and the Weligama surf breaks are all within forty minutes.",
      "Galle is also the end of the Southern Expressway: Colombo is about an hour and a half away, and the airport around two and a quarter, which makes it a comfortable final stop before a late flight.",
    ],
    interests: ["culture", "food", "beach"],
    bestMonths: [12, 1, 2, 3],
    shoulderMonths: [4, 7, 8, 11],
    avoidMonths: [5, 6, 9, 10],
    seasonNote:
      "South-west coast pattern: best December to March. May and June are the wettest months and the sea is rough.",
    suggestedNights: 2,
    image: ownedPhotos.surfSouthCoast,
    highlights: [
      "The rampart walk at sunset",
      "The lighthouse and Flag Rock bastion",
      "Dutch Reformed Church and the Maritime Museum",
      "Independent shops and cafés inside the walls",
      "A cooking class in a fort courtyard",
    ],
    travel: [
      { to: "unawatuna", minutes: 20 },
      { to: "mirissa", minutes: 55 },
      { to: "hikkaduwa", minutes: 40 },
      { to: "colombo", minutes: 95, note: "Via the Southern Expressway (E01)." },
      { to: "yala", minutes: 160 },
      { to: "udawalawe", minutes: 150 },
    ],
    coordinates: { lat: 6.0535, lng: 80.221 },
    experienceSlugs: ["galle-fort-walking-tour", "sri-lankan-cooking-class"],
    nearbySlugs: ["unawatuna", "mirissa", "hikkaduwa"],
    appeal: 92,
  },
  {
    slug: "unawatuna",
    name: "Unawatuna",
    region: "south-coast",
    tagline: "A curved bay twenty minutes from the fort",
    summary:
      "Unawatuna is the closest proper beach to Galle: a sheltered crescent of sand with a reef that keeps the water calm enough to swim most of the season. It is busy and built-up along the shore, and still one of the easiest places on the south coast to do very little for three days.",
    description: [
      "The bay is protected by a reef, which makes it one of the safer swimming beaches on this coast during the main season. Jungle Beach, on the far side of Rumassala hill, is quieter and reachable on foot or by tuk-tuk.",
      "Rumassala itself is worth the climb for the Japanese Peace Pagoda and the view back over the bay. Local legend ties the hill to the Ramayana, and it holds a surprising concentration of medicinal plants.",
      "Koggala, fifteen minutes east, is where you will see stilt fishermen. Be aware that most of the poles now belong to men who fish for photographs rather than fish; agree a price first, and treat it as a portrait sitting rather than a documentary moment.",
      "The stretch between Unawatuna and Weligama is the heart of the south-coast food scene — rice and curry, fresh seafood, and cooking classes in family homes.",
    ],
    interests: ["beach", "food", "wellness"],
    bestMonths: [12, 1, 2, 3],
    shoulderMonths: [4, 7, 8, 11],
    avoidMonths: [5, 6, 9, 10],
    seasonNote:
      "Calmest swimming December to March. The bay gets rough and narrow during the south-west monsoon from May.",
    suggestedNights: 2,
    image: ownedPhotos.surfSouthCoast,
    highlights: [
      "Swimming in the reef-sheltered bay",
      "Jungle Beach and the Japanese Peace Pagoda",
      "Koggala's stilt fishermen at golden hour",
      "Seafood on the sand and a home cooking class",
      "Twenty minutes from Galle Fort",
    ],
    travel: [
      { to: "galle", minutes: 20 },
      { to: "mirissa", minutes: 40 },
      { to: "hikkaduwa", minutes: 55 },
      { to: "colombo", minutes: 110 },
    ],
    coordinates: { lat: 6.0094, lng: 80.2497 },
    experienceSlugs: ["stilt-fishing-koggala", "sri-lankan-cooking-class"],
    nearbySlugs: ["galle", "mirissa", "hikkaduwa"],
    appeal: 74,
  },
  {
    slug: "mirissa",
    name: "Mirissa",
    region: "south-coast",
    tagline: "Blue whales offshore, palm trees leaning over the sand",
    summary:
      "Mirissa is the south coast's whale-watching harbour and its best-known crescent beach. Blue whales pass close to the continental shelf here between roughly November and April, and the village behind the bay has grown into a comfortable base for beach days, surf lessons at Weligama and sunset on Coconut Tree Hill.",
    description: [
      "Boats leave the fishery harbour around 6.30am for a three to five hour trip. Sightings of blue whales and spinner dolphins are common in season but never guaranteed, and the sea can be uncomfortable — take something for seasickness if you are prone to it.",
      "Choose an operator that keeps its distance. Crowding and chasing whales is both stressful for the animals and against the guidelines; responsible boats stay back, cut engines and wait.",
      "Weligama, ten minutes west, has a long sandy-bottomed beach break that is the best beginner surf in the country. Boards and lessons are available on the sand for very little.",
      "Coconut Tree Hill at the eastern end of the bay is the photograph everyone comes for. Go at sunrise rather than sunset if you would like it to yourself.",
    ],
    interests: ["beach", "wildlife", "adventure"],
    bestMonths: [12, 1, 2, 3],
    shoulderMonths: [4, 11],
    avoidMonths: [5, 6, 7, 8, 9, 10],
    seasonNote:
      "Whale watching runs roughly November to April, which is also when the sea is calmest. Most boats stop during the south-west monsoon.",
    suggestedNights: 2,
    image: ownedPhotos.surfSouthCoast,
    highlights: [
      "Blue whale and dolphin watching from the harbour",
      "Beginner surf lessons at Weligama Bay",
      "Coconut Tree Hill at first light",
      "Parrot Rock and the fishing harbour",
      "Seafood grills along the beach at night",
    ],
    travel: [
      { to: "unawatuna", minutes: 40 },
      { to: "galle", minutes: 55 },
      { to: "yala", minutes: 150 },
      { to: "udawalawe", minutes: 120 },
      { to: "ella", minutes: 240 },
      { to: "colombo", minutes: 140 },
    ],
    coordinates: { lat: 5.9483, lng: 80.4589 },
    experienceSlugs: ["mirissa-whale-watching", "weligama-surf-lesson"],
    nearbySlugs: ["unawatuna", "galle", "udawalawe"],
    appeal: 86,
  },
  {
    slug: "hikkaduwa",
    name: "Hikkaduwa",
    region: "south-coast",
    tagline: "Coral, turtles and the island's oldest surf town",
    summary:
      "Hikkaduwa was Sri Lanka's first backpacker beach and still has the most relaxed, least polished feel of the south-west resorts. A shallow marine sanctuary sits directly off the main beach, green turtles feed in the surf line most mornings, and the reef break in front of town is forgiving.",
    description: [
      "The coral sanctuary can be snorkelled straight from the beach. It has suffered from bleaching and from decades of boat traffic, so expect a modest reef rather than a spectacular one — and use reef-safe sunscreen, or none at all.",
      "Green turtles come in to feed on seagrass close to shore, particularly in the morning. Watch them in the water rather than handling them, and give the commercial 'turtle hatcheries' along this coast a sceptical look: standards vary widely and several keep animals in conditions that do them no good.",
      "The surf is a mixed beach and reef setup that suits improvers, with a handful of gentler spots for beginners. Season runs with the rest of the south-west coast, November to April.",
      "Hikkaduwa is the closest good beach to Colombo — about 85 minutes on the expressway — which makes it a practical first or last stop on a short trip.",
    ],
    interests: ["beach", "nature", "adventure", "wellness"],
    bestMonths: [12, 1, 2, 3],
    shoulderMonths: [4, 11],
    avoidMonths: [5, 6, 7, 8, 9, 10],
    seasonNote:
      "Snorkelling and surf are at their best November to April. The sea is rough and murky during the south-west monsoon.",
    suggestedNights: 2,
    image: ownedPhotos.surfSouthCoast,
    highlights: [
      "Snorkelling the coral sanctuary from the beach",
      "Green turtles feeding in the shallows at dawn",
      "A forgiving reef break for improving surfers",
      "Seenigama temple on its island offshore",
      "The shortest run to a beach from Colombo",
    ],
    travel: [
      { to: "galle", minutes: 40 },
      { to: "unawatuna", minutes: 55 },
      { to: "colombo", minutes: 85 },
      { to: "mirissa", minutes: 80 },
    ],
    coordinates: { lat: 6.1395, lng: 80.1063 },
    experienceSlugs: ["hikkaduwa-reef-snorkelling", "ayurveda-wellness-retreat"],
    nearbySlugs: ["galle", "unawatuna", "colombo"],
    appeal: 64,
  },
  /* ----------------------------------------------------------- wilderness */
  {
    slug: "yala",
    name: "Yala National Park",
    region: "wilderness",
    tagline: "The best chance of a leopard anywhere on earth",
    summary:
      "Yala's Block 1 has the highest recorded density of leopards in the world, along with sloth bears, elephants, crocodiles and a coastline of lagoons and dunes. It is also the most visited park in the country, so the experience depends heavily on going at the right time with the right driver.",
    description: [
      "Drives leave at 5.30am and again mid-afternoon, and last four to five hours. Mornings are better for cats and for light; afternoons are quieter for jeep numbers. A full-day permit avoids the gate rush entirely.",
      "Block 1 is where the leopard density is highest and where the jeeps concentrate. Block 5 and the adjoining Lunugamvehera park are far less busy and worth asking about if you would rather have space than certainty.",
      "Yala's Block 1 usually closes for around six weeks from the start of September for maintenance and drought relief. Always confirm current dates before building a trip around it — the closure moves.",
      "Tissamaharama is the practical base, with everything from guesthouses to the tented and villa-style camps on the park boundary. A stay inside or on the edge of the park buys you first position at the gate.",
    ],
    interests: ["wildlife", "nature", "adventure"],
    bestMonths: [2, 3, 4, 5, 6, 7],
    shoulderMonths: [1, 8, 12],
    avoidMonths: [9, 10, 11],
    seasonNote:
      "Sightings are best in the dry months February to July, when animals concentrate at waterholes. Block 1 normally closes for around six weeks from early September — confirm before booking.",
    suggestedNights: 2,
    image: ownedPhotos.jungleVilla,
    highlights: [
      "Dawn game drive in Block 1 for leopard",
      "Sloth bear sightings in the palu fruiting season",
      "Elephants, crocodiles and wading birds on the lagoons",
      "Staying in a tented camp on the park boundary",
      "Kirinda and the coastal dunes",
    ],
    travel: [
      { to: "udawalawe", minutes: 90 },
      { to: "mirissa", minutes: 150 },
      { to: "ella", minutes: 150 },
      { to: "galle", minutes: 160 },
      { to: "arugam-bay", minutes: 210, note: "Inland via Monaragala; the coastal track is not a through route." },
    ],
    coordinates: { lat: 6.3735, lng: 81.5089 },
    experienceSlugs: ["yala-leopard-safari", "yala-jungle-villa-stay"],
    nearbySlugs: ["udawalawe", "ella", "mirissa"],
    appeal: 88,
  },
  {
    slug: "udawalawe",
    name: "Udawalawe National Park",
    region: "wilderness",
    tagline: "Elephants, all year, almost guaranteed",
    summary:
      "Udawalawe is open grassland and scrub around a large reservoir, and it holds a resident elephant population of several hundred. Sightings are close to certain in any month, the terrain is open enough that you actually see what is there, and it is far less crowded than Yala.",
    description: [
      "Because the park is open rather than thick forest, Udawalawe is the most reliable place in Sri Lanka to watch elephant behaviour rather than just glimpse an animal — family groups at the water, sub-adults sparring, and large solitary tuskers.",
      "There are no leopards to speak of here, but there are water buffalo, spotted deer, jackals, crocodiles and exceptional birdlife, including large numbers of raptors over the grassland.",
      "The Elephant Transit Home nearby rehabilitates orphaned calves for release back into the wild and holds public feeding sessions at set times through the day. It is a genuine conservation operation and, unlike some elephant attractions, there is no riding or bathing with animals.",
      "Udawalawe sits neatly between the hill country and the south coast, which makes it easy to slot into a route without a long detour.",
    ],
    interests: ["wildlife", "nature"],
    bestMonths: [5, 6, 7, 8, 9],
    shoulderMonths: [1, 2, 3, 4, 12],
    avoidMonths: [10, 11],
    seasonNote:
      "Elephants are seen year-round. The driest, easiest months are May to September; October and November can be wet and the tracks muddy.",
    suggestedNights: 1,
    image: ownedPhotos.jungleVilla,
    highlights: [
      "Near-certain wild elephant sightings on an open grassland drive",
      "The Elephant Transit Home feeding sessions",
      "Raptors and water birds over the reservoir",
      "A short, easy stop between the hills and the coast",
    ],
    travel: [
      { to: "yala", minutes: 90 },
      { to: "ella", minutes: 120 },
      { to: "mirissa", minutes: 120 },
      { to: "galle", minutes: 150 },
      { to: "colombo", minutes: 225 },
    ],
    coordinates: { lat: 6.4389, lng: 80.8886 },
    experienceSlugs: ["udawalawe-elephant-safari"],
    nearbySlugs: ["yala", "ella", "mirissa"],
    appeal: 76,
  },
  {
    slug: "wilpattu",
    name: "Wilpattu National Park",
    region: "wilderness",
    tagline: "The biggest park, the fewest jeeps, the land of lakes",
    summary:
      "Wilpattu is Sri Lanka's largest and oldest national park, named for the villus — natural sand-rimmed lakes — scattered through its dense dry forest. It has leopards, sloth bears and elephants, and a fraction of Yala's traffic. Sightings take longer here, and feel earned when they come.",
    description: [
      "The forest is thicker than Yala's, so game viewing is slower and more patient. The reward is the atmosphere: long tracks with no other vehicle in sight, and villus that fill after rain and draw everything to them.",
      "Sloth bears are a particular draw in June and July when the palu trees fruit. Leopards are present in good numbers and are increasingly seen as the population has recovered since the park fully reopened in 2010.",
      "Wilpattu is about an hour from Anuradhapura and three hours from Negombo, which makes it the natural wildlife stop for anyone travelling the western side of the island or heading north.",
      "The park closes or becomes difficult during the north-east monsoon, roughly late October to January, when tracks flood.",
    ],
    interests: ["wildlife", "nature"],
    bestMonths: [2, 3, 4, 5, 6, 7],
    shoulderMonths: [8, 9],
    avoidMonths: [10, 11, 12, 1],
    seasonNote:
      "Best February to July, with sloth bears most active in June and July. Tracks flood during the north-east monsoon from late October.",
    suggestedNights: 1,
    image: ownedPhotos.jungleVilla,
    highlights: [
      "Villu lakes and dry-zone forest with very few vehicles",
      "Sloth bears in the palu fruiting season",
      "Leopards for patient watchers",
      "An easy add-on to Anuradhapura",
    ],
    travel: [
      { to: "anuradhapura", minutes: 75 },
      { to: "negombo", minutes: 180 },
      { to: "colombo", minutes: 215 },
      { to: "jaffna", minutes: 225 },
    ],
    coordinates: { lat: 8.45, lng: 80.05 },
    experienceSlugs: ["wilpattu-wilderness-safari"],
    nearbySlugs: ["anuradhapura", "negombo", "jaffna"],
    appeal: 60,
  },
  /* ----------------------------------------------------------- east coast */
  {
    slug: "arugam-bay",
    name: "Arugam Bay",
    region: "east-coast",
    tagline: "One of Asia's great right-hand point breaks",
    summary:
      "Arugam Bay is a single sandy road behind a long right-hand point break, and from May to September it is one of the best and most consistent surf destinations in Asia. Out of season it empties almost completely. Kumana National Park and a string of lagoons sit within a short tuk-tuk ride.",
    description: [
      "Main Point is the wave that made the place: a long, workable right that breaks over sand and rock and holds a crowd. Beginners are better off at Baby Point or Whiskey Point a little north, where boards and lessons are easy to arrange.",
      "The season is sharply defined. From roughly April or May to September the swell is consistent and the weather dry; from November to March the surf dies, the rain arrives and many places shut for the season.",
      "Beyond the surf, Kumana National Park is an hour south and is one of the island's best bird sites, with a large mangrove lagoon that fills with painted storks, pelicans and spoonbills. Elephants and the occasional leopard cross the road on the way there.",
      "Arugam Bay is remote — about three hours from Ella and five to six from Yala or Trincomalee — so it works best as a place you commit several days to rather than pass through.",
    ],
    interests: ["beach", "adventure", "wellness"],
    bestMonths: [5, 6, 7, 8, 9],
    shoulderMonths: [4, 10],
    avoidMonths: [11, 12, 1, 2, 3],
    seasonNote:
      "Surf season runs roughly May to September, which is exactly when the south-west coast is wet. Many businesses close from November to March.",
    suggestedNights: 3,
    image: ownedPhotos.surfSouthCoast,
    highlights: [
      "Main Point's long right-hand wall",
      "Beginner surf at Baby Point and Whiskey Point",
      "Kumana National Park's bird lagoons",
      "Elephant Rock and the lagoons at sunset",
      "Yoga and a slow pace between sessions",
    ],
    travel: [
      { to: "ella", minutes: 180 },
      { to: "yala", minutes: 210, note: "Inland via Monaragala." },
      { to: "trincomalee", minutes: 300, note: "Long coastal run via Batticaloa — split it or start very early." },
    ],
    coordinates: { lat: 6.84, lng: 81.836 },
    experienceSlugs: ["arugam-bay-surf-session"],
    nearbySlugs: ["ella", "yala", "trincomalee"],
    appeal: 72,
  },
  {
    slug: "trincomalee",
    name: "Trincomalee",
    region: "east-coast",
    tagline: "One of the world's great natural harbours, and the calmest water on the island",
    summary:
      "Trincomalee sits on a deep natural harbour with the Koneswaram temple on a cliff above it and the flat, clear beaches of Uppuveli and Nilaveli to the north. Pigeon Island's coral lies a short boat ride offshore, and between May and September the sea here is glassy while the south-west is being rained on.",
    description: [
      "Koneswaram Kovil, on Swami Rock above the harbour, is one of the most important Hindu temples in Sri Lanka and among the most dramatically sited anywhere — a painted gopuram on a cliff straight above the Indian Ocean.",
      "Nilaveli and Uppuveli are wide, shallow and unusually calm, which makes them the best swimming beaches on the island for families and weak swimmers during the eastern season.",
      "Pigeon Island National Park, a few hundred metres offshore from Nilaveli, has the best accessible coral and reef fish in the country, along with resident blacktip reef sharks in the shallows. Visitor numbers are capped and the reef is fragile: no standing on coral, no touching, no sunscreen in the water.",
      "Whale and dolphin watching runs out of Trincomalee in the eastern season, and Kanniya's hot wells and the hot springs make an easy inland half-day.",
    ],
    interests: ["beach", "nature", "wildlife"],
    bestMonths: [5, 6, 7, 8],
    shoulderMonths: [3, 4, 9],
    avoidMonths: [10, 11, 12, 1, 2],
    seasonNote:
      "The eastern season runs roughly April to September. The north-east monsoon makes October to January wet and the sea rough.",
    suggestedNights: 2,
    image: ownedPhotos.surfSouthCoast,
    highlights: [
      "Snorkelling Pigeon Island's reef",
      "Koneswaram temple on Swami Rock",
      "Calm, shallow swimming at Nilaveli and Uppuveli",
      "Blue whales and dolphins in the eastern season",
      "Kanniya hot wells",
    ],
    travel: [
      { to: "polonnaruwa", minutes: 125 },
      { to: "sigiriya", minutes: 165 },
      { to: "anuradhapura", minutes: 165 },
      { to: "jaffna", minutes: 240 },
      { to: "arugam-bay", minutes: 300 },
    ],
    coordinates: { lat: 8.5874, lng: 81.2152 },
    experienceSlugs: ["pigeon-island-snorkelling", "koneswaram-temple-visit"],
    nearbySlugs: ["polonnaruwa", "sigiriya", "jaffna"],
    appeal: 70,
  },
  /* ---------------------------------------------------------------- north */
  {
    slug: "jaffna",
    name: "Jaffna",
    region: "north",
    tagline: "Palmyra, kovils and a cuisine of its own",
    summary:
      "The Jaffna peninsula is flat, bright and culturally Tamil, with its own food, festivals and architecture, and a landscape of palmyra palms, lagoons and islands. Long closed by the civil war, it is now easily reached by road or by a comfortable day train from Colombo, and it feels like a different country to the south.",
    description: [
      "Nallur Kandaswamy Kovil is the peninsula's centre of gravity — a large, active Hindu temple with daily pujas and a spectacular 25-day festival in July and August. Men remove shirts to enter; everyone removes shoes.",
      "The Dutch fort on the lagoon, the public library rebuilt after its destruction in 1981, and the markets of the old town give Jaffna its texture. The library in particular carries a weight of recent history that is worth understanding before you visit.",
      "Jaffna food is distinct from the south: more chilli, more tamarind, crab curry, odiyal kool, and palmyra products from jaggery to toddy. It is one of the best reasons to make the trip.",
      "Beyond the town, causeways run out to the islands — Kayts, Karainagar and, at the end of a long road and a short ferry, Delft with its wild ponies and coral-block walls. Nagadeepa's Buddhist temple and Nainativu's Hindu shrine sit on the same small island and are visited together.",
    ],
    interests: ["culture", "food"],
    bestMonths: [2, 3, 4, 7, 8, 9],
    shoulderMonths: [5, 6],
    avoidMonths: [10, 11, 12, 1],
    seasonNote:
      "Dry from February to September, and very hot in May and June. The north-east monsoon soaks the peninsula from October to January.",
    suggestedNights: 2,
    image: ownedPhotos.tuktukRoadTrip,
    highlights: [
      "Evening puja at Nallur Kandaswamy Kovil",
      "Jaffna crab curry and palmyra sweets",
      "The Dutch fort and the rebuilt public library",
      "The island causeways to Kayts and Karainagar",
      "Delft's wild ponies and coral-block walls",
    ],
    travel: [
      { to: "anuradhapura", minutes: 210 },
      { to: "trincomalee", minutes: 240 },
      { to: "wilpattu", minutes: 225 },
      { to: "colombo", minutes: 390, note: "The day train from Colombo Fort is more comfortable than the drive." },
    ],
    coordinates: { lat: 9.6615, lng: 80.0255 },
    experienceSlugs: ["jaffna-peninsula-tour"],
    nearbySlugs: ["anuradhapura", "trincomalee", "wilpattu"],
    appeal: 56,
  },
];
