import type { TripPackage } from "@/lib/types";
import { ownedPhotos } from "@/content/destinations";

/**
 * Pre-planned packages (FR-3).
 *
 * Routing rules every package here obeys:
 *  - No single day exceeds 300 minutes (5 hours) of driving.
 *  - Days run in a geographically coherent order with no backtracking.
 *  - Arrival and departure days assume Bandaranaike International Airport (CMB),
 *    which is beside Negombo, roughly 45 minutes north of Colombo.
 *  - `driveMinutes` on a day that travels by train is still the *road* estimate,
 *    so that totals stay comparable; the summary makes the train explicit.
 *
 * `bestMonths` is the intersection of what the route's regions can honestly
 * support. The east-and-north package deliberately runs in the opposite season
 * to everything else, because that is when that side of the island is at its best.
 */
export const trips: readonly TripPackage[] = [
  {
    slug: "cultural-triangle-express",
    name: "Cultural Triangle Express",
    tagline: "Four days, three ancient capitals, one very large rock",
    summary:
      "The highest-value short trip in Sri Lanka for anyone whose interest is history. Sigiriya, Dambulla and Polonnaruwa sit within an hour of each other, so you see three World Heritage Sites without ever facing a long drive. Built for stopovers and business extensions.",
    durationDays: 4,
    tier: "short",
    interests: ["culture", "adventure"],
    destinationSlugs: ["sigiriya", "polonnaruwa", "dambulla"],
    days: [
      {
        day: 1,
        title: "Airport to Sigiriya",
        destinationSlug: "sigiriya",
        summary:
          "Met at the airport and driven north through coconut country and the Kurunegala hills to Sigiriya village, about four hours. Settle in, and climb nothing today.",
        experienceSlugs: [],
        overnightIn: "sigiriya",
        driveMinutes: 240,
      },
      {
        day: 2,
        title: "Pidurangala at dawn, Sigiriya at opening time",
        destinationSlug: "sigiriya",
        summary:
          "Up at 5am for the scramble onto Pidurangala and the first light on Sigiriya, back for breakfast, then the 1,200 steps to Kassapa's summit palace before the heat. The afternoon is yours.",
        experienceSlugs: ["pidurangala-sunrise", "sigiriya-sunrise-climb"],
        overnightIn: "sigiriya",
        driveMinutes: 0,
      },
      {
        day: 3,
        title: "Polonnaruwa by bicycle",
        destinationSlug: "polonnaruwa",
        summary:
          "An early run east to the twelfth-century capital, then three hours on a bicycle under the trees between the Quadrangle, the great stupas and the Gal Vihara Buddhas. Back to Sigiriya for the evening.",
        experienceSlugs: ["polonnaruwa-cycle-tour"],
        overnightIn: "sigiriya",
        driveMinutes: 150,
      },
      {
        day: 4,
        title: "Dambulla caves and the road home",
        destinationSlug: "dambulla",
        summary:
          "The five painted cave shrines at Dambulla on the way south, lunch in town, and back to the airport in the afternoon. Allow four hours for the drive.",
        experienceSlugs: ["dambulla-cave-temple"],
        overnightIn: null,
        driveMinutes: 265,
      },
    ],
    includes: [
      "Private vehicle and English-speaking driver throughout",
      "Three nights' accommodation in Sigiriya",
      "Daily breakfast",
      "Licensed site guides at Sigiriya, Polonnaruwa and Dambulla",
      "Bicycle hire at Polonnaruwa",
    ],
    excludes: [
      "International flights and visa",
      "Site entrance fees, which are significant at Sigiriya",
      "Lunches, dinners and drinks",
      "Travel insurance",
      "Tips",
    ],
    priceBandPerPerson: "$",
    bestMonths: [1, 2, 3, 5, 6, 7, 8, 9],
    image: ownedPhotos.sigiriyaSunrise,
  },
  {
    slug: "southern-shortcut",
    name: "Southern Shortcut",
    tagline: "Five days of fort walls, whales and warm water",
    summary:
      "Galle and the south coast are ninety minutes from Colombo on the expressway, which makes this the easiest short trip on the island. A Dutch fort, a cooking class, a first surf lesson and a dawn boat out to the blue whales, with nothing that feels rushed.",
    durationDays: 5,
    tier: "short",
    interests: ["beach", "culture", "food", "wildlife"],
    destinationSlugs: ["galle", "mirissa"],
    days: [
      {
        day: 1,
        title: "Airport to Galle Fort",
        destinationSlug: "galle",
        summary:
          "Straight onto the Southern Expressway and down the coast, about two and a half hours from the airport. Check in inside the ramparts and walk them at sunset.",
        experienceSlugs: [],
        overnightIn: "galle",
        driveMinutes: 155,
      },
      {
        day: 2,
        title: "Inside the ramparts",
        destinationSlug: "galle",
        summary:
          "A morning walking tour of the fort — the Dutch Reformed Church, the warehouses, the lighthouse — then a hands-on cooking class that starts at the market and ends with lunch you made.",
        experienceSlugs: ["galle-fort-walking-tour", "sri-lankan-cooking-class"],
        overnightIn: "galle",
        driveMinutes: 0,
      },
      {
        day: 3,
        title: "Down the coast to Mirissa",
        destinationSlug: "mirissa",
        summary:
          "An hour east along the coast road, stopping at the Koggala stilt fishermen on the way. Afternoon surf lesson in the shallow sandy bay at Weligama.",
        experienceSlugs: ["stilt-fishing-koggala", "weligama-surf-lesson"],
        overnightIn: "mirissa",
        driveMinutes: 60,
      },
      {
        day: 4,
        title: "Blue whales at first light",
        destinationSlug: "mirissa",
        summary:
          "Out of the harbour at 6.30am into deep water for blue whales and spinner dolphins, back by lunch, and the rest of the day on the sand. Coconut Tree Hill at sunset.",
        experienceSlugs: ["mirissa-whale-watching"],
        overnightIn: "mirissa",
        driveMinutes: 0,
      },
      {
        day: 5,
        title: "Mirissa to the airport",
        destinationSlug: "mirissa",
        summary: "A slow morning on the beach and a three-hour run back up the expressway to the airport.",
        experienceSlugs: [],
        overnightIn: null,
        driveMinutes: 185,
      },
    ],
    includes: [
      "Private vehicle and English-speaking driver on transfer days",
      "Four nights' accommodation, two in Galle Fort and two in Mirissa",
      "Daily breakfast",
      "Galle Fort guided walk",
      "Cooking class with market visit and lunch",
      "Whale watching boat with a marine guide",
      "Two-hour beginner surf lesson",
    ],
    excludes: [
      "International flights and visa",
      "Most lunches and all dinners",
      "Alcoholic drinks",
      "Travel insurance",
      "Tips",
    ],
    priceBandPerPerson: "$$",
    bestMonths: [12, 1, 2, 3],
    image: ownedPhotos.surfSouthCoast,
  },
  {
    slug: "classic-sri-lanka",
    name: "Classic Sri Lanka",
    tagline: "Ten days: the rock, the temple, the train and the whales",
    summary:
      "The route almost every first-time visitor should take, in the order that makes geographic sense. Cultural Triangle, Kandy, the hill-country train to Ella, an elephant safari on the way down, and three nights on the south coast to finish. Nothing more than four hours in the car on any day.",
    durationDays: 10,
    tier: "classic",
    interests: ["culture", "nature", "wildlife", "beach"],
    destinationSlugs: ["negombo", "sigiriya", "dambulla", "kandy", "ella", "udawalawe", "mirissa", "galle"],
    days: [
      {
        day: 1,
        title: "Arrive Negombo",
        destinationSlug: "negombo",
        summary:
          "Twenty-five minutes from the airport to the beach. Sleep off the flight, walk the sand, eat some seafood, and start properly tomorrow.",
        experienceSlugs: [],
        overnightIn: "negombo",
        driveMinutes: 30,
      },
      {
        day: 2,
        title: "North to Sigiriya",
        destinationSlug: "sigiriya",
        summary:
          "Four hours north into the dry zone, past reservoirs built fifteen hundred years ago. Arrive in time for a late-afternoon walk in the village and your first sight of the rock.",
        experienceSlugs: [],
        overnightIn: "sigiriya",
        driveMinutes: 240,
      },
      {
        day: 3,
        title: "Sigiriya rock and the elephant gathering",
        destinationSlug: "sigiriya",
        summary:
          "At the gate for 7am and up to the summit palace before the heat. In the afternoon, a jeep out onto the Minneriya grassland where the herds gather at the receding reservoir.",
        experienceSlugs: ["sigiriya-sunrise-climb", "minneriya-elephant-gathering"],
        overnightIn: "sigiriya",
        driveMinutes: 60,
      },
      {
        day: 4,
        title: "Dambulla caves, then Kandy",
        destinationSlug: "dambulla",
        summary:
          "The painted cave temples in the morning, then two hours south into the hills to Kandy, arriving for the evening puja at the Temple of the Sacred Tooth Relic.",
        experienceSlugs: ["dambulla-cave-temple", "temple-of-the-tooth"],
        overnightIn: "kandy",
        driveMinutes: 140,
      },
      {
        day: 5,
        title: "Kandy",
        destinationSlug: "kandy",
        summary:
          "The botanic gardens at Peradeniya in the morning — orchid house, giant bamboo, the great Javan fig — and an afternoon walking the lake and the market.",
        experienceSlugs: ["royal-botanic-gardens-peradeniya"],
        overnightIn: "kandy",
        driveMinutes: 30,
      },
      {
        day: 6,
        title: "The hill-country train to Ella",
        destinationSlug: "ella",
        summary:
          "One of the great railway journeys: six hours climbing through tea estates, tunnels and waterfalls to Ella. Luggage goes ahead by road so you travel with a daypack.",
        experienceSlugs: ["kandy-to-ella-train"],
        overnightIn: "ella",
        driveMinutes: 240,
      },
      {
        day: 7,
        title: "Ella",
        destinationSlug: "ella",
        summary:
          "Little Adam's Peak for sunrise, down through the tea to the Nine Arch Bridge in time for a train, and an afternoon doing very little at all.",
        experienceSlugs: ["little-adams-peak-and-nine-arch"],
        overnightIn: "ella",
        driveMinutes: 0,
      },
      {
        day: 8,
        title: "Elephants at Udawalawe, then the coast",
        destinationSlug: "udawalawe",
        summary:
          "Down out of the hills to Udawalawe for a morning jeep drive among several hundred wild elephants, then on to Mirissa for the first of two nights by the sea.",
        experienceSlugs: ["udawalawe-elephant-safari"],
        overnightIn: "mirissa",
        driveMinutes: 240,
      },
      {
        day: 9,
        title: "Mirissa",
        destinationSlug: "mirissa",
        summary:
          "Out at dawn for blue whales, back for a long lunch, and the afternoon on the beach. Coconut Tree Hill at sunset if you can still move.",
        experienceSlugs: ["mirissa-whale-watching"],
        overnightIn: "mirissa",
        driveMinutes: 0,
      },
      {
        day: 10,
        title: "Galle Fort and the flight home",
        destinationSlug: "galle",
        summary:
          "An hour west to Galle for a last walk inside the ramparts and lunch in a courtyard, then three hours up the expressway to the airport.",
        experienceSlugs: ["galle-fort-walking-tour"],
        overnightIn: null,
        driveMinutes: 245,
      },
    ],
    includes: [
      "Private vehicle and English-speaking driver throughout",
      "Nine nights' accommodation",
      "Daily breakfast",
      "Reserved seats on the Kandy–Ella train, with luggage forwarded by road",
      "Jeep safaris at Minneriya and Udawalawe",
      "Whale watching boat at Mirissa",
      "Licensed guides at Sigiriya, Dambulla, Kandy and Galle",
    ],
    excludes: [
      "International flights and visa",
      "Site and park entrance fees",
      "Lunches and dinners",
      "Drinks",
      "Travel insurance",
      "Tips",
    ],
    priceBandPerPerson: "$$",
    bestMonths: [12, 1, 2, 3, 4],
    image: ownedPhotos.sigiriyaSunrise,
  },
  {
    slug: "tea-trains-and-a-beach-finish",
    name: "Tea, Trains and a Beach Finish",
    tagline: "Eight days in the hills, ending with your feet in the sea",
    summary:
      "For travellers who would rather walk in tea country than queue at a ruin. Kandy, the high estates around Nuwara Eliya, World's End at dawn, the train down to Ella, and then a fast drop to the south coast for two nights of doing nothing.",
    durationDays: 8,
    tier: "classic",
    interests: ["nature", "food", "adventure", "beach"],
    destinationSlugs: ["kandy", "nuwara-eliya", "horton-plains", "ella", "udawalawe", "mirissa"],
    days: [
      {
        day: 1,
        title: "Airport to Kandy",
        destinationSlug: "kandy",
        summary:
          "Three hours inland and uphill to the old royal capital. If the timing works, go straight to the evening puja at the Temple of the Sacred Tooth Relic.",
        experienceSlugs: ["temple-of-the-tooth"],
        overnightIn: "kandy",
        driveMinutes: 185,
      },
      {
        day: 2,
        title: "Kandy",
        destinationSlug: "kandy",
        summary:
          "Peradeniya's botanic gardens in the cool of the morning, then the lake circuit, the covered market and the climb to the Bahiravakanda Buddha for the view.",
        experienceSlugs: ["royal-botanic-gardens-peradeniya"],
        overnightIn: "kandy",
        driveMinutes: 30,
      },
      {
        day: 3,
        title: "Up to the tea country",
        destinationSlug: "nuwara-eliya",
        summary:
          "Nearly three hours of switchbacks to 1,868 metres, stopping at Ramboda Falls. An afternoon walking a working estate and following the leaf through the factory to the tasting table.",
        experienceSlugs: ["tea-estate-and-factory-tour"],
        overnightIn: "nuwara-eliya",
        driveMinutes: 165,
      },
      {
        day: 4,
        title: "World's End before the cloud",
        destinationSlug: "horton-plains",
        summary:
          "A 5am start for Horton Plains and the 9 km loop across the montane grassland to a 900-metre drop, returning by Baker's Falls. Back in Nuwara Eliya by early afternoon.",
        experienceSlugs: ["horton-plains-worlds-end"],
        overnightIn: "nuwara-eliya",
        driveMinutes: 150,
      },
      {
        day: 5,
        title: "The train to Ella",
        destinationSlug: "ella",
        summary:
          "Board at Nanu Oya for the best three hours of the hill-country line — Pattipola, the Idalgashinna ridge and the drop into the Uva basin. Luggage follows by road.",
        experienceSlugs: ["kandy-to-ella-train"],
        overnightIn: "ella",
        driveMinutes: 120,
      },
      {
        day: 6,
        title: "Ella",
        destinationSlug: "ella",
        summary:
          "Sunrise yoga on a deck over the gap, then Little Adam's Peak and the walk down to the Nine Arch Bridge. Ella Rock instead if you want the harder day.",
        experienceSlugs: ["ella-yoga-morning", "little-adams-peak-and-nine-arch"],
        overnightIn: "ella",
        driveMinutes: 0,
      },
      {
        day: 7,
        title: "Elephants, then the sea",
        destinationSlug: "udawalawe",
        summary:
          "Down the escarpment to Udawalawe for a morning among wild elephants on the open grassland, then two more hours to the south coast and a room facing the water.",
        experienceSlugs: ["udawalawe-elephant-safari"],
        overnightIn: "mirissa",
        driveMinutes: 240,
      },
      {
        day: 8,
        title: "Mirissa to the airport",
        destinationSlug: "mirissa",
        summary: "A swim, a long breakfast, and three hours up the expressway to the airport.",
        experienceSlugs: [],
        overnightIn: null,
        driveMinutes: 185,
      },
    ],
    includes: [
      "Private vehicle and English-speaking driver throughout",
      "Seven nights' accommodation, including two in a tea-estate bungalow",
      "Daily breakfast",
      "Reserved train seats from Nanu Oya to Ella, luggage forwarded by road",
      "Tea estate and factory tour with tasting",
      "Horton Plains guided loop with packed breakfast",
      "Udawalawe jeep safari",
    ],
    excludes: [
      "International flights and visa",
      "National park and site entrance fees",
      "Lunches and dinners",
      "Drinks",
      "Travel insurance",
      "Tips",
    ],
    priceBandPerPerson: "$$",
    bestMonths: [12, 1, 2, 3, 4],
    image: ownedPhotos.ellaRoadSign,
  },
  {
    slug: "wildlife-and-beaches",
    name: "Wildlife and Beaches",
    tagline: "Ten days of leopards, elephants, whales and reef",
    summary:
      "A south-coast and wilderness route for people who would rather look at animals than architecture. Turtles off Hikkaduwa, blue whales at Mirissa, elephants at Udawalawe and two full days in Yala, with Galle Fort at either end to remind you there is a country attached.",
    durationDays: 10,
    tier: "classic",
    interests: ["wildlife", "beach", "nature"],
    destinationSlugs: ["negombo", "hikkaduwa", "galle", "mirissa", "udawalawe", "yala"],
    days: [
      {
        day: 1,
        title: "Arrive Negombo",
        destinationSlug: "negombo",
        summary: "Half an hour from the aircraft door to the beach. An early night, and a boat on the lagoon if you land in the morning.",
        experienceSlugs: ["negombo-lagoon-and-canal-boat"],
        overnightIn: "negombo",
        driveMinutes: 30,
      },
      {
        day: 2,
        title: "South to Hikkaduwa",
        destinationSlug: "hikkaduwa",
        summary:
          "Around Colombo and onto the expressway, a little over two hours to the island's oldest surf town. Afternoon in the water.",
        experienceSlugs: [],
        overnightIn: "hikkaduwa",
        driveMinutes: 140,
      },
      {
        day: 3,
        title: "Turtles and coral",
        destinationSlug: "hikkaduwa",
        summary:
          "Snorkel the marine sanctuary straight off the beach, where green turtles feed in water you can stand up in, then a lazy afternoon and a reef break session for improvers.",
        experienceSlugs: ["hikkaduwa-reef-snorkelling"],
        overnightIn: "hikkaduwa",
        driveMinutes: 0,
      },
      {
        day: 4,
        title: "Galle Fort",
        destinationSlug: "galle",
        summary:
          "Forty minutes down the coast to the ramparts. A guided walk through the fort in the late afternoon, finishing on the wall for sunset.",
        experienceSlugs: ["galle-fort-walking-tour"],
        overnightIn: "galle",
        driveMinutes: 40,
      },
      {
        day: 5,
        title: "On to Mirissa",
        destinationSlug: "mirissa",
        summary:
          "An hour east with a stop at the Koggala stilt fishermen, then the afternoon on the sand and an early night before the boat.",
        experienceSlugs: ["stilt-fishing-koggala"],
        overnightIn: "mirissa",
        driveMinutes: 60,
      },
      {
        day: 6,
        title: "Blue whales",
        destinationSlug: "mirissa",
        summary:
          "Out of the harbour before dawn to the shelf edge for blue whales, sperm whales and spinner dolphins. Back by lunch, and nothing else planned.",
        experienceSlugs: ["mirissa-whale-watching"],
        overnightIn: "mirissa",
        driveMinutes: 0,
      },
      {
        day: 7,
        title: "Udawalawe",
        destinationSlug: "udawalawe",
        summary:
          "Two hours inland to the open grassland and an afternoon jeep drive among several hundred wild elephants, with the Transit Home feeding session beforehand.",
        experienceSlugs: ["udawalawe-elephant-safari"],
        overnightIn: "udawalawe",
        driveMinutes: 120,
      },
      {
        day: 8,
        title: "Into Yala",
        destinationSlug: "yala",
        summary:
          "Ninety minutes east to the park boundary and a thatched villa in the forest. Afternoon game drive into Block 1, then dinner under the trees.",
        experienceSlugs: ["yala-jungle-villa-stay"],
        overnightIn: "yala",
        driveMinutes: 90,
      },
      {
        day: 9,
        title: "Dawn in Block 1",
        destinationSlug: "yala",
        summary:
          "First through the gate at 6am for the best hour of the day for leopard, sloth bear and elephant, back to the villa for a long, hot, entirely unproductive afternoon.",
        experienceSlugs: ["yala-leopard-safari"],
        overnightIn: "yala",
        driveMinutes: 0,
      },
      {
        day: 10,
        title: "Yala to the airport",
        destinationSlug: "yala",
        summary:
          "A last early drive if you want one, then west along the coast and up the expressway. Allow five hours, so an evening flight suits this day best.",
        experienceSlugs: [],
        overnightIn: null,
        driveMinutes: 295,
      },
    ],
    includes: [
      "Private vehicle and English-speaking driver throughout",
      "Nine nights' accommodation, including two on the Yala boundary",
      "Daily breakfast, plus all meals at the Yala property",
      "Three jeep safaris with driver-trackers",
      "Whale watching boat at Mirissa",
      "Guided snorkelling at Hikkaduwa",
      "Galle Fort guided walk",
    ],
    excludes: [
      "International flights and visa",
      "National park entrance fees, which are the largest single extra on this route",
      "Most lunches and dinners outside Yala",
      "Drinks",
      "Travel insurance",
      "Tips",
    ],
    priceBandPerPerson: "$$$",
    bestMonths: [12, 1, 2, 3, 4],
    image: ownedPhotos.jungleVilla,
  },
  {
    slug: "grand-island-loop",
    name: "The Grand Island Loop",
    tagline: "Fifteen days, four kingdoms, two mountains and a whale",
    summary:
      "The full circuit, unhurried. Anuradhapura and Polonnaruwa with time to actually look at them, three nights in the Cultural Triangle, Kandy, the tea country and Horton Plains, the train to Ella, a safari on the way down and three nights on the south coast to finish.",
    durationDays: 15,
    tier: "grand",
    interests: ["culture", "nature", "wildlife", "beach", "food"],
    destinationSlugs: [
      "negombo",
      "anuradhapura",
      "sigiriya",
      "polonnaruwa",
      "dambulla",
      "kandy",
      "nuwara-eliya",
      "horton-plains",
      "ella",
      "udawalawe",
      "mirissa",
      "galle",
    ],
    days: [
      {
        day: 1,
        title: "Arrive Negombo",
        destinationSlug: "negombo",
        summary: "Land, drive twenty-five minutes, sleep. Nothing else is required of you today.",
        experienceSlugs: [],
        overnightIn: "negombo",
        driveMinutes: 30,
      },
      {
        day: 2,
        title: "North to Anuradhapura",
        destinationSlug: "anuradhapura",
        summary:
          "Three and a half hours north into the dry zone. Arrive in the afternoon and go straight to the Ruwanwelisaya for the evening pilgrimage, which is when the sacred city makes sense.",
        experienceSlugs: [],
        overnightIn: "anuradhapura",
        driveMinutes: 195,
      },
      {
        day: 3,
        title: "The sacred city",
        destinationSlug: "anuradhapura",
        summary:
          "A full day across a capital that ran for a thousand years: Isurumuniya, the Twin Ponds, Abhayagiri, the great stupas and the Sri Maha Bodhi, paced around the heat.",
        experienceSlugs: ["anuradhapura-sacred-city-tour"],
        overnightIn: "anuradhapura",
        driveMinutes: 40,
      },
      {
        day: 4,
        title: "East to Sigiriya",
        destinationSlug: "sigiriya",
        summary:
          "Under two hours across the plain to Sigiriya village. An afternoon cycling the paddy and tank bunds, and an early night before the climb.",
        experienceSlugs: [],
        overnightIn: "sigiriya",
        driveMinutes: 110,
      },
      {
        day: 5,
        title: "Two rocks",
        destinationSlug: "sigiriya",
        summary:
          "Pidurangala in the dark for first light on the fortress, breakfast, and then Sigiriya itself — frescoes, mirror wall, lion's paws and the summit palace.",
        experienceSlugs: ["pidurangala-sunrise", "sigiriya-sunrise-climb"],
        overnightIn: "sigiriya",
        driveMinutes: 0,
      },
      {
        day: 6,
        title: "Polonnaruwa",
        destinationSlug: "polonnaruwa",
        summary:
          "An early run east and a morning on a bicycle among the ruins of the twelfth-century capital, finishing at the Gal Vihara. Afternoon back at Sigiriya, or a jeep onto the Minneriya grassland.",
        experienceSlugs: ["polonnaruwa-cycle-tour", "minneriya-elephant-gathering"],
        overnightIn: "sigiriya",
        driveMinutes: 150,
      },
      {
        day: 7,
        title: "Dambulla, then down to Kandy",
        destinationSlug: "dambulla",
        summary:
          "The painted caves in the morning, lunch in Dambulla, then two hours into the hills, arriving in Kandy for the evening puja.",
        experienceSlugs: ["dambulla-cave-temple", "temple-of-the-tooth"],
        overnightIn: "kandy",
        driveMinutes: 140,
      },
      {
        day: 8,
        title: "Kandy",
        destinationSlug: "kandy",
        summary:
          "Peradeniya's gardens in the morning, the lake and the market in the afternoon, and Kandyan drumming and dance in the evening if you want it.",
        experienceSlugs: ["royal-botanic-gardens-peradeniya"],
        overnightIn: "kandy",
        driveMinutes: 30,
      },
      {
        day: 9,
        title: "Into the tea country",
        destinationSlug: "nuwara-eliya",
        summary:
          "The first leg of the hill railway to Nanu Oya, then an afternoon on a working estate and through the factory to the tasting table.",
        experienceSlugs: ["kandy-to-ella-train", "tea-estate-and-factory-tour"],
        overnightIn: "nuwara-eliya",
        driveMinutes: 165,
      },
      {
        day: 10,
        title: "World's End",
        destinationSlug: "horton-plains",
        summary:
          "A 5am start onto the plateau and the loop to the escarpment before the cloud closes it, returning past Baker's Falls. The afternoon is for a fire and a pot of tea.",
        experienceSlugs: ["horton-plains-worlds-end"],
        overnightIn: "nuwara-eliya",
        driveMinutes: 150,
      },
      {
        day: 11,
        title: "The train down to Ella",
        destinationSlug: "ella",
        summary:
          "Three hours on the most photographed stretch of railway in Asia, over Pattipola and along the Idalgashinna ridge into the Uva basin.",
        experienceSlugs: ["kandy-to-ella-train"],
        overnightIn: "ella",
        driveMinutes: 120,
      },
      {
        day: 12,
        title: "Ella",
        destinationSlug: "ella",
        summary:
          "Little Adam's Peak at sunrise and the Nine Arch Bridge below it, or Ella Rock if you want the long version. Yoga on a deck over the gap in the afternoon.",
        experienceSlugs: ["little-adams-peak-and-nine-arch", "ella-yoga-morning"],
        overnightIn: "ella",
        driveMinutes: 0,
      },
      {
        day: 13,
        title: "Elephants and the run to the coast",
        destinationSlug: "udawalawe",
        summary:
          "Out of the hills to Udawalawe for a morning jeep drive on the grassland, then two hours more to the south coast.",
        experienceSlugs: ["udawalawe-elephant-safari"],
        overnightIn: "mirissa",
        driveMinutes: 240,
      },
      {
        day: 14,
        title: "Mirissa",
        destinationSlug: "mirissa",
        summary:
          "Blue whales at dawn, then a surf lesson at Weligama or a hammock, depending on how the last two weeks have gone.",
        experienceSlugs: ["mirissa-whale-watching", "weligama-surf-lesson"],
        overnightIn: "mirissa",
        driveMinutes: 0,
      },
      {
        day: 15,
        title: "Galle, and home",
        destinationSlug: "galle",
        summary:
          "An hour west for a last morning inside the ramparts and lunch in a fort courtyard, then three hours to the airport.",
        experienceSlugs: ["galle-fort-walking-tour"],
        overnightIn: null,
        driveMinutes: 245,
      },
    ],
    includes: [
      "Private vehicle and English-speaking driver throughout",
      "Fourteen nights' accommodation, including a tea-estate bungalow and a fort house",
      "Daily breakfast",
      "Reserved train seats on both hill-country legs, luggage forwarded by road",
      "Two jeep safaris and one whale watching boat",
      "Licensed guides at Anuradhapura, Sigiriya, Polonnaruwa, Dambulla, Kandy and Galle",
    ],
    excludes: [
      "International flights and visa",
      "Site and national park entrance fees",
      "Lunches and dinners",
      "Drinks",
      "Travel insurance",
      "Tips",
    ],
    priceBandPerPerson: "$$$",
    bestMonths: [12, 1, 2, 3],
    image: ownedPhotos.sigiriyaSunrise,
  },
  {
    slug: "east-coast-and-the-north",
    name: "East Coast and the North",
    tagline: "Thirteen days on the other side of the monsoon",
    summary:
      "Built for June, July and August, when the south-west is wet and the east and north are at their best. Anuradhapura, the Jaffna peninsula, Pigeon Island's coral, Polonnaruwa and Sigiriya, finishing in Kandy. The Sri Lanka that returning travellers come back for.",
    durationDays: 13,
    tier: "grand",
    interests: ["culture", "beach", "food", "nature"],
    destinationSlugs: ["negombo", "anuradhapura", "jaffna", "trincomalee", "polonnaruwa", "sigiriya", "kandy"],
    days: [
      {
        day: 1,
        title: "Arrive Negombo",
        destinationSlug: "negombo",
        summary: "Twenty-five minutes from the airport, a night by the lagoon, and a long way north tomorrow.",
        experienceSlugs: [],
        overnightIn: "negombo",
        driveMinutes: 30,
      },
      {
        day: 2,
        title: "To Anuradhapura",
        destinationSlug: "anuradhapura",
        summary:
          "Three and a half hours north, arriving in time to walk the sacred precinct at dusk with the evening pilgrims.",
        experienceSlugs: [],
        overnightIn: "anuradhapura",
        driveMinutes: 195,
      },
      {
        day: 3,
        title: "The sacred city",
        destinationSlug: "anuradhapura",
        summary:
          "A full day among the stupas, monasteries and bathing ponds of a capital that lasted a millennium, ending at the Sri Maha Bodhi.",
        experienceSlugs: ["anuradhapura-sacred-city-tour"],
        overnightIn: "anuradhapura",
        driveMinutes: 40,
      },
      {
        day: 4,
        title: "North to Jaffna",
        destinationSlug: "jaffna",
        summary:
          "Three and a half hours up the A9 through the Vanni to the peninsula. The landscape, the language and the food all change on the way.",
        experienceSlugs: [],
        overnightIn: "jaffna",
        driveMinutes: 210,
      },
      {
        day: 5,
        title: "The peninsula and the islands",
        destinationSlug: "jaffna",
        summary:
          "Nallur Kandaswamy Kovil, the Dutch fort, the rebuilt library and the causeways out to the islands, with a Jaffna crab curry in the middle of it.",
        experienceSlugs: ["jaffna-peninsula-tour"],
        overnightIn: "jaffna",
        driveMinutes: 90,
      },
      {
        day: 6,
        title: "Across to Trincomalee",
        destinationSlug: "trincomalee",
        summary:
          "Four hours east and south along the coast road to one of the world's great natural harbours. Sunset from Swami Rock below the Koneswaram temple.",
        experienceSlugs: ["koneswaram-temple-visit"],
        overnightIn: "trincomalee",
        driveMinutes: 240,
      },
      {
        day: 7,
        title: "Pigeon Island",
        destinationSlug: "trincomalee",
        summary:
          "On the first boat out to the reef for the best accessible coral in the country, blacktip reef sharks in the shallows, and back to Nilaveli for the afternoon.",
        experienceSlugs: ["pigeon-island-snorkelling"],
        overnightIn: "trincomalee",
        driveMinutes: 40,
      },
      {
        day: 8,
        title: "Nilaveli",
        destinationSlug: "trincomalee",
        summary:
          "A day with nothing in it: flat, shallow, warm water, a long beach, and the hot wells at Kanniya if you want an hour of purpose.",
        experienceSlugs: [],
        overnightIn: "trincomalee",
        driveMinutes: 0,
      },
      {
        day: 9,
        title: "Polonnaruwa, then Sigiriya",
        destinationSlug: "polonnaruwa",
        summary:
          "Two hours inland to the medieval capital and a morning on a bicycle among its ruins, then on to Sigiriya village for the night.",
        experienceSlugs: ["polonnaruwa-cycle-tour"],
        overnightIn: "sigiriya",
        driveMinutes: 200,
      },
      {
        day: 10,
        title: "Sigiriya",
        destinationSlug: "sigiriya",
        summary:
          "At the gate for 7am and up to the summit palace, then an afternoon jeep drive at Minneriya, which is at its best in exactly these months.",
        experienceSlugs: ["sigiriya-sunrise-climb", "minneriya-elephant-gathering"],
        overnightIn: "sigiriya",
        driveMinutes: 60,
      },
      {
        day: 11,
        title: "Down to Kandy",
        destinationSlug: "kandy",
        summary:
          "Two and a half hours south into the hills, arriving for the evening puja at the Temple of the Sacred Tooth Relic.",
        experienceSlugs: ["temple-of-the-tooth"],
        overnightIn: "kandy",
        driveMinutes: 155,
      },
      {
        day: 12,
        title: "Kandy",
        destinationSlug: "kandy",
        summary:
          "Peradeniya's botanic gardens, the lake, the market, and a last dinner looking down over the town.",
        experienceSlugs: ["royal-botanic-gardens-peradeniya"],
        overnightIn: "kandy",
        driveMinutes: 30,
      },
      {
        day: 13,
        title: "Kandy to the airport",
        destinationSlug: "kandy",
        summary: "Three hours down out of the hills to the airport, with a spice garden stop at Matale if the flight is late.",
        experienceSlugs: [],
        overnightIn: null,
        driveMinutes: 185,
      },
    ],
    includes: [
      "Private vehicle and English-speaking driver throughout",
      "Twelve nights' accommodation",
      "Daily breakfast",
      "Guided day across the Jaffna peninsula with lunch",
      "Pigeon Island boat and snorkelling equipment",
      "Minneriya jeep safari",
      "Licensed guides at Anuradhapura, Polonnaruwa, Sigiriya and Kandy",
    ],
    excludes: [
      "International flights and visa",
      "Site and national park entrance fees",
      "Most lunches and all dinners",
      "Drinks",
      "Travel insurance",
      "Tips",
    ],
    priceBandPerPerson: "$$",
    bestMonths: [5, 6, 7, 8, 9],
    image: ownedPhotos.tuktukRoadTrip,
  },
];
